// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FKidpxhdsQwWp4nULMSjFSbMYfxuWNQ',
    appId: '1:858114947674:web:a7fae3912afb49f9fc7663',
    messagingSenderId: '858114947674',
    projectId: 'fir-authconfig',
    authDomain: 'fir-authconfig.firebaseapp.com',
    storageBucket: 'fir-authconfig.firebasestorage.app',
    measurementId: 'G-2QT765H5M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRX4APQNxDUg701fkTIocnXnTN7inj7vk',
    appId: '1:858114947674:android:0c98d780fcd93326fc7663',
    messagingSenderId: '858114947674',
    projectId: 'fir-authconfig',
    storageBucket: 'fir-authconfig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_52QdNaQXkyKUAanGEpIHy8dsCd-PLYQ',
    appId: '1:858114947674:ios:c91c54c7d1b81961fc7663',
    messagingSenderId: '858114947674',
    projectId: 'fir-authconfig',
    storageBucket: 'fir-authconfig.firebasestorage.app',
    iosBundleId: 'com.firebaseauthconfig.firebaseAuthConfig',
  );
}
